CREATE TABLE IF NOT EXISTS strategy_template (
  id UUID PRIMARY KEY,
  template_key TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  channel_mix_json JSONB NOT NULL,
  campaign_structure_json JSONB NOT NULL,
  creative_angles_json JSONB NOT NULL,
  kpi_targets_json JSONB NOT NULL,
  risk_factors_json JSONB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS strategy_run_intel (
  id UUID PRIMARY KEY,
  request_id UUID NOT NULL,
  business_id UUID NOT NULL REFERENCES business_profile(id),
  objective TEXT NOT NULL,
  monthly_budget NUMERIC NOT NULL,
  chosen_template_key TEXT NOT NULL,
  decision_path_json JSONB NOT NULL,
  confidence_score INT NOT NULL CHECK (confidence_score BETWEEN 0 AND 100),
  score_breakdown_json JSONB NOT NULL,
  similarity_match_json JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO strategy_template (id, template_key, name, description, channel_mix_json, campaign_structure_json, creative_angles_json, kpi_targets_json, risk_factors_json)
VALUES
(gen_random_uuid(),'OFFLINE_HIGH_TICKET_TRUST_GOOGLE_LOCAL','Offline High Ticket Trust + Google Local','For premium offline businesses focused on trust building and local intent.',
 '{"google":70,"meta":20,"youtube":10,"tiktok":0}'::jsonb,
 '{"top":"Search high-intent","mid":"Reviews + testimonials","bottom":"Call/visit optimization"}'::jsonb,
 '["expert authority","customer proof","local trust"]'::jsonb,
 '{"targetCPL":"high-intent","targetROAS":"2.5+"}'::jsonb,
 '["small search volume","high CPC"]'::jsonb),
(gen_random_uuid(),'OFFLINE_MID_TICKET_FESTIVAL_FOOTFALL','Offline Mid Ticket Festival Footfall','Seasonal offline campaigns for footfall growth.',
 '{"meta":50,"google":40,"youtube":10,"tiktok":0}'::jsonb,
 '{"top":"Awareness bursts","mid":"Offer reminders","bottom":"Store visit CTA"}'::jsonb,
 '["festival offer","scarcity","community"]'::jsonb,
 '{"targetCPL":"moderate","targetROAS":"2.0+"}'::jsonb,
 '["seasonality swings"]'::jsonb),
(gen_random_uuid(),'OFFLINE_LOW_TICKET_IMPULSE_PROMO','Offline Low Ticket Impulse Promo','Low ticket local promos optimized for quick conversions.',
 '{"meta":60,"google":30,"youtube":0,"tiktok":10}'::jsonb,
 '{"top":"Local reach","mid":"Promo reminders","bottom":"Instant redemption"}'::jsonb,
 '["price-led hook","limited time"]'::jsonb,
 '{"targetCPL":"low","targetROAS":"1.8+"}'::jsonb,
 '["discount dependency"]'::jsonb),
(gen_random_uuid(),'ONLINE_MID_TICKET_META_FUNNEL_RETARGET','Online Mid Ticket Meta Funnel + Retarget','Balanced online funnel with retargeting for efficient growth.',
 '{"meta":60,"google":25,"youtube":10,"tiktok":5}'::jsonb,
 '{"top":"Prospecting","mid":"Retargeting","bottom":"Offer close"}'::jsonb,
 '["problem-solution","social proof","benefit stack"]'::jsonb,
 '{"targetCPL":"moderate","targetROAS":"2.2+"}'::jsonb,
 '["creative fatigue"]'::jsonb),
(gen_random_uuid(),'ONLINE_HIGH_TICKET_LEADGEN_APPOINTMENT','Online High Ticket Leadgen Appointment','Lead generation with qualification and appointment booking.',
 '{"google":45,"meta":45,"youtube":10,"tiktok":0}'::jsonb,
 '{"top":"Lead magnet","mid":"Qualification","bottom":"Appointment booking"}'::jsonb,
 '["authority","case study","ROI framing"]'::jsonb,
 '{"targetCPL":"qualified","targetROAS":"3.0+"}'::jsonb,
 '["long sales cycle"]'::jsonb),
(gen_random_uuid(),'ONLINE_LOW_TICKET_UGC_BUNDLES','Online Low Ticket UGC Bundles','Low ticket ecom playbook using UGC and bundles.',
 '{"meta":55,"tiktok":30,"google":10,"youtube":5}'::jsonb,
 '{"top":"UGC discovery","mid":"Bundle value","bottom":"Cart close"}'::jsonb,
 '["UGC demo","bundle savings","fast shipping"]'::jsonb,
 '{"targetCPL":"low","targetROAS":"2.0+"}'::jsonb,
 '["discount sensitivity","ad fatigue"]'::jsonb)
ON CONFLICT (template_key) DO NOTHING;
